<?php

	echo "ldap_control_paged_result()";

	ldap_control_paged_result();

	substr('asldkj');

	sprintf('something'.ldap_control_paged_result($parameter));

// checklist
        // PHP Core
        'hex2bin' => null,
        'http_response_code' => null,
        'get_declared_traits' => null,
        'getimagesizefromstring' => null,
        'stream_set_chunk_size' => null,
        'socket_import_stream' => null,
        'trait_exists' => null,
        'header_register_callback' => null,
        // SPL
        'class_uses' => null,
        // Session
        'session_status' => null,
        'session_register_shutdown' => null,
        // Mysqli
        'mysqli_error_list' => null,
        'mysqli_stmt_error_list' => null,
        // Libxml
        'libxml_set_external_entity_loader' => null,
        // LDAP
        'ldap_control_paged_result' => null,
        'ldap_control_paged_result_response' => null,
        // Intl
        'transliterator_create' => null,
        'transliterator_create_from_rules' => null,
        'transliterator_create_inverse' => null,
        'transliterator_get_error_code' => null,
        'transliterator_get_error_message' => null,
        'transliterator_list_ids' => null,
        'transliterator_transliterate' => null,
        // Zlib
        'zlib_decode' => null,
        'zlib_encode' => null,